@startuml

component Registry
component Gateway
component NumberAPI
component BookAPI
database MongoDB
database PostgreSQL

Gateway ..> NumberAPI
Gateway ..> BookAPI

Gateway .> PostgreSQL
BookAPI ..> MongoDB
BookAPI .> NumberAPI

@enduml
