version: '2'
services:
    bookweb-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/bookweb/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=bookweb
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
